options:
  merge-default-rules: false
  formatter: stylish
files:
  ignore:
    - './_dev/node_modules/**'
rules:
  clean-import-paths:
    - 2
    - leading-underscore: false
    - filename-extension: false
  hex-length:
    - 0
    - style: 'short'
  indentation:
    - 2
    - size: 4
  leading-zero:
    - 2
    - include: false
  url-quotes:
    - 0
